---
chef_automate_deploy_automate: true
chef_automate_deploy_chef_server: true
chef_automate_cli_path: /tmp
chef_automate_hostname: automate.chef.lab
chef_automate_username: jtonello
chef_automate_longusername: John Tonello
chef_automate_useremail: jtonello@chef.lab
chef_automate_userpassword: password
chef_automate_orgname: lab
chef_automate_longorgname: Chef Lab
