---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ chef_automate_hostname }}"
  become: true
- name: Set kernel parameter vm.max_map_count
  ansible.builtin.shell:
    cmd: sysctl -w vm.max_map_count=262144
  become: true
  register: sysctl_max_map_count
  changed_when: sysctl_max_map_count.rc != 0
- name: Set kernel parameter vm.dirty_expire_centisecs
  ansible.builtin.shell:
    cmd: sysctl -w vm.dirty_expire_centisecs=20000
  become: true
  register: sysctl_dirty_expire
  changed_when: sysctl_dirty_expire.rc != 0
- name: Download Chef Automate CLI
  ansible.builtin.get_url:
    url: https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip
    dest: /tmp/chef-automate_linux_amd64.zip
    mode: "0644"
- name: Extract Chef Automate CLI
  ansible.builtin.shell:
    cmd: gunzip < /tmp/chef-automate_linux_amd64.zip > {{ chef_automate_cli_path }}/chef-automate && chmod +x {{ chef_automate_cli_path }}/chef-automate
  args:
    creates: "{{ chef_automate_cli_path }}/chef-automate"
  register: extract_cli
  changed_when: extract_cli.rc == 0 and extract_cli.stdout != ""
- name: Deploy Chef Automate and Chef Infra Server
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product automate --product infra-server --accept-terms-and-mlsa=true
    chdir: "{{ chef_automate_cli_path }}"
  args:
    creates: /hab
  become: true
  register: deploy_automate
  changed_when: deploy_automate.rc == 0
  when: chef_automate_deploy_automate | bool
- name: Deploy Chef Infra Server only
  ansible.builtin.command:
    cmd: ./chef-automate deploy --product infra-server --accept-terms-and-mlsa=true
    chdir: "{{ chef_automate_cli_path }}"
  args:
    creates: /hab
  become: true
  register: deploy_chef_server
  changed_when: deploy_chef_server.rc == 0
  when: chef_automate_deploy_chef_server | bool and not chef_automate_deploy_automate | bool
- name: Create Chef admin user
  ansible.builtin.command:
    cmd: "chef-server-ctl user-create  {{ chef_automate_username }}  {{ chef_automate_longusername | quote }}  {{ chef_automate_useremail | quote }}  {{ chef_automate_userpassword
      | quote }}  --filename {{ chef_automate_cli_path }}/{{ chef_automate_username }}.pem\n"
    chdir: "{{ chef_automate_cli_path }}"
  args:
    creates: "{{ chef_automate_cli_path }}/{{ chef_automate_username }}.pem"
  become: true
  register: create_user
  changed_when: create_user.rc == 0 and create_user.stdout != ""
- name: Create Chef organization
  ansible.builtin.command:
    cmd: "chef-server-ctl org-create  {{ chef_automate_orgname }}  {{ chef_automate_longorgname | quote }}  --association_user {{ chef_automate_username }}  --filename
      {{ chef_automate_cli_path }}/{{ chef_automate_orgname }}-validator.pem\n"
    chdir: "{{ chef_automate_cli_path }}"
  args:
    creates: "{{ chef_automate_cli_path }}/{{ chef_automate_orgname }}-validator.pem"
  become: true
  register: create_org
  changed_when: create_org.rc == 0 and create_org.stdout != ""
